######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 16 23:34:50 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += detectdialog.h
FORMS += detectdialog.ui
SOURCES += detectdialog.cpp main.cpp
